#PBS -N Leith1_k0
#PBS -l nodes=1:ppn=28
#PBS -l walltime=720:00:00
#PBS -q batch
#PBS -V
#PBS -S /bin/bash 
          

          
### intel mpi 
source /public/software/profile.d/mpi_mvapich2-2.2b-intel.sh

cd $PBS_O_WORKDIR
EXEC=/public/home/qianyk/MITgcm_c66g/verification/barotropicDGTest/cartRL_advSchemes/Leith1_k0/mitgcmuv

NSLOTS=`cat $PBS_NODEFILE | wc -l`
echo "This jobs is "$PBS_JOBID@$PBS_QUEUE" "$NSLOTS" "$PBS_NODEFILE


time -p mpirun -np 28 -machinefile $PBS_NODEFILE  $EXEC

